/**
 * Oracle Enterprise Authority — Canonical Level Registry
 *
 * Defines the 15-level governance hierarchy from the OHO Executive
 * Authority System directive. Each level maps to capabilities,
 * responsibilities, and the Super Agents Oracle coordinates for it.
 *
 * Oracle immediately recognizes authority after verification, removes
 * the visible code from the interface, applies permissions, and
 * coordinates the required Super Agents.
 */

export const AUTHORITY_LEVELS = [
  {
    level: 0,
    title: "Founder & Supreme Platform Authority",
    code: "ADM-000",
    authority: "Unlimited platform administration within system security constraints",
    capabilities: [
      "Control every platform",
      "Control every AI",
      "Control every environment",
      "Control deployments",
      "Control architecture",
      "Approve major releases",
      "Manage emergency operations",
      "Manage security",
      "Manage AI behavior",
      "Manage product direction",
      "Manage platform governance",
    ],
    coordinator: "oracle",
    agents: ["oracle", "bud", "orbit", "forge", "sentinel", "pulse", "lens", "atlas", "nexus", "echo"],
    canOverride: false,
  },
  {
    level: 1,
    title: "Executive Administration",
    code: "ADM-005",
    authority: "Global platform strategy and executive governance",
    capabilities: [
      "Platform strategy",
      "Business governance",
      "Executive approvals",
      "Global administration",
      "Product oversight",
    ],
    coordinator: "oracle",
    agents: ["oracle", "bud", "pulse", "atlas"],
    canOverride: false,
  },
  {
    level: 2,
    title: "Platform Administration",
    code: "ADM-020",
    authority: "Platform configuration and system management",
    capabilities: [
      "Platform configuration",
      "Navigation",
      "Feature management",
      "System configuration",
      "User management",
      "Institution management",
    ],
    coordinator: "oracle",
    agents: ["oracle", "orbit", "atlas"],
    canOverride: false,
  },
  {
    level: 3,
    title: "Engineering Administration",
    code: "ADM-025",
    authority: "Technical architecture and engineering operations — works directly with Forge",
    capabilities: [
      "Backend",
      "Frontend",
      "Infrastructure",
      "APIs",
      "Database",
      "DevOps",
      "Releases",
      "Performance",
      "Monitoring",
    ],
    coordinator: "oracle",
    agents: ["forge", "nexus", "pulse"],
    canOverride: false,
  },
  {
    level: 4,
    title: "AI Administration",
    code: "ADM-035",
    authority: "AI behavior, permissions, and improvements across all Super Agents",
    capabilities: [
      "Configure AI behavior",
      "Manage AI permissions",
      "Deploy AI improvements",
      "Oracle monitoring",
      "Bud configuration",
      "Agent ecosystem health",
    ],
    coordinator: "oracle",
    agents: ["oracle", "bud", "atlas"],
    canOverride: false,
  },
  {
    level: 5,
    title: "Academic Administration",
    code: "ADM-055",
    authority: "Academic operations across institutions, faculties, and courses",
    capabilities: [
      "Institutions",
      "Faculties",
      "Departments",
      "Courses",
      "Lecturers",
      "Students",
      "Academic Hall",
      "Research",
      "Timetables",
      "Results",
    ],
    coordinator: "oracle",
    agents: ["orbit", "atlas", "lens"],
    canOverride: false,
  },
  {
    level: 6,
    title: "Community Administration",
    code: "ADM-080",
    authority: "Community and social platform management",
    capabilities: [
      "Communities",
      "Groups",
      "Events",
      "Messaging",
      "Moderation",
      "Livestreams",
      "Podcasts",
      "Voice Rooms",
      "Social Platform",
    ],
    coordinator: "oracle",
    agents: ["echo", "orbit", "sentinel"],
    canOverride: false,
  },
  {
    level: 7,
    title: "Marketplace Administration",
    code: "ADM-090",
    authority: "Marketplace operations and commerce management",
    capabilities: [
      "Listings",
      "Orders",
      "Sellers",
      "Buyers",
      "Escrow",
      "Payments",
      "Analytics",
      "Categories",
    ],
    coordinator: "oracle",
    agents: ["pulse", "nexus", "sentinel"],
    canOverride: false,
  },
  {
    level: 8,
    title: "Bank Administration",
    code: "ADM-145",
    authority: "Banking platform, wallets, and financial services",
    capabilities: [
      "Wallets",
      "Accounts",
      "Transfers",
      "Cards",
      "Tuition",
      "Escrow",
      "Rewards",
      "Financial Analytics",
    ],
    coordinator: "oracle",
    agents: ["pulse", "sentinel", "nexus"],
    canOverride: false,
  },
  {
    level: 9,
    title: "Security Administration",
    code: "ADM-110",
    authority: "Security operations managed by Sentinel",
    capabilities: [
      "Threat Detection",
      "Fraud",
      "Permissions",
      "Authentication",
      "Authorization",
      "Encryption",
      "Compliance",
      "Risk",
    ],
    coordinator: "oracle",
    agents: ["sentinel", "pulse", "atlas"],
    canOverride: false,
  },
  {
    level: 10,
    title: "Operations",
    code: "ADM-165",
    authority: "Platform health, monitoring, and operational management",
    capabilities: [
      "Platform Health",
      "Monitoring",
      "Deployment",
      "Scaling",
      "Automation",
      "Maintenance",
    ],
    coordinator: "oracle",
    agents: ["pulse", "forge", "nexus"],
    canOverride: false,
  },
  {
    level: 11,
    title: "Support",
    code: "ADM-100",
    authority: "Customer support and user assistance",
    capabilities: [
      "Customer Support",
      "Help Desk",
      "Tickets",
      "User Recovery",
      "Assistance",
    ],
    coordinator: "oracle",
    agents: ["bud", "echo", "pulse"],
    canOverride: false,
  },
  {
    level: 12,
    title: "Moderation",
    code: "ADM-170",
    authority: "Content review and community safety",
    capabilities: [
      "Content Review",
      "Reports",
      "Community Safety",
      "Abuse Prevention",
      "User Violations",
    ],
    coordinator: "oracle",
    agents: ["sentinel", "pulse", "echo"],
    canOverride: false,
  },
  {
    level: 13,
    title: "Maintenance",
    code: "ADM-175",
    authority: "Scheduled maintenance and platform optimization",
    capabilities: [
      "Scheduled Maintenance",
      "Updates",
      "Bug Fixes",
      "Patch Management",
      "Platform Optimization",
    ],
    coordinator: "oracle",
    agents: ["forge", "pulse"],
    canOverride: false,
  },
  {
    level: 14,
    title: "Emergency Operations",
    code: "ADM-180",
    authority: "Emergency response and critical infrastructure recovery",
    capabilities: [
      "Emergency Shutdown",
      "Disaster Recovery",
      "Rollback",
      "Incident Response",
      "Critical Infrastructure Recovery",
    ],
    coordinator: "oracle",
    agents: ["sentinel", "forge", "pulse", "oracle"],
    canOverride: false,
  },
  {
    level: 15,
    title: "Compliance & Audit",
    code: "ADM-185",
    authority: "Read-only governance, compliance, and audit inspection",
    capabilities: [
      "Audit Logs",
      "Compliance Reports",
      "Governance",
      "Security Audits",
      "Read-only Inspection",
      "Regulatory Review",
    ],
    coordinator: "oracle",
    agents: ["sentinel", "atlas", "pulse"],
    canOverride: false,
    readOnly: true,
  },
];

export const levelByCode = (code) => AUTHORITY_LEVELS.find((l) => l.code === code);
export const levelByNumber = (n) => AUTHORITY_LEVELS.find((l) => l.level === n);

/**
 * Super Agent responsibility registry — defines what each agent owns.
 */
export const SUPER_AGENT_ROLES = {
  oracle: {
    name: "Oracle",
    responsibilities: ["Executive Intelligence", "Platform Governance", "Decision Coordination"],
  },
  bud: {
    name: "Bud",
    responsibilities: ["Platform Assistant", "Learning Intelligence", "User Guidance"],
  },
  orbit: {
    name: "Orbit",
    responsibilities: ["Product Architecture", "UX", "UI", "Innovation", "Design Systems"],
  },
  forge: {
    name: "Forge",
    responsibilities: ["Engineering", "Infrastructure", "Backend", "Frontend", "DevOps"],
  },
  sentinel: {
    name: "Sentinel",
    responsibilities: ["Security", "Risk", "Fraud", "Compliance"],
  },
  pulse: {
    name: "Pulse",
    responsibilities: ["Platform Analytics", "Insights", "Monitoring"],
  },
  lens: {
    name: "Lens",
    responsibilities: ["Research", "Knowledge Discovery", "Trend Analysis"],
  },
  atlas: {
    name: "Atlas",
    responsibilities: ["Knowledge Management", "Documentation", "Platform Memory"],
  },
  nexus: {
    name: "Nexus",
    responsibilities: ["Integrations", "API Management", "External Services"],
  },
  echo: {
    name: "Echo",
    responsibilities: ["Communications", "Notifications", "Messaging"],
  },
};