import React from "react";
import { motion } from "framer-motion";
import BudCharacter from "@/components/brand/BudCharacter";
import SectionHeader from "@/components/me/SectionHeader";

const EASE = [0.16, 1, 0.3, 1];

/**
 * LearningInsights — personalized observations generated by Spark
 * and presented naturally by Bud.
 */
export default function LearningInsights({ sessions, courses }) {
  const insights = buildInsights(sessions || [], courses || []);
  return (
    <div>
      <SectionHeader title="Learning Insights" />
      <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, ease: EASE }} className="glass-card p-5">
        <div className="flex items-center gap-2.5 mb-3">
          <div className="w-9 h-9 rounded-full glass-strong overflow-hidden ring-1 ring-primary/20">
            <BudCharacter animate={false} glow={false} className="w-full h-full" />
          </div>
          <p className="text-[13px] font-semibold text-foreground">Bud's observations</p>
        </div>
        <div className="space-y-2.5">
          {insights.map((t, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, x: -8 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: i * 0.08, duration: 0.4 }}
              className="flex gap-2.5 p-3 rounded-2xl bg-primary/8 border border-primary/15"
            >
              <span className="w-1.5 h-1.5 rounded-full bg-primary mt-1.5 flex-shrink-0" />
              <p className="text-[13px] text-foreground/90 leading-relaxed">{t}</p>
            </motion.div>
          ))}
        </div>
      </motion.div>
    </div>
  );
}

function buildInsights(sessions, courses) {
  const out = [];
  const bySubject = {};
  sessions.forEach((s) => {
    const k = s.subject || (s.courses && s.courses[0]) || s.course_code;
    if (k) bySubject[k] = (bySubject[k] || 0) + (s.duration_minutes || 0);
  });
  const top = Object.entries(bySubject).sort((a, b) => b[1] - a[1])[0];
  if (top) out.push(`${top[0]} is becoming one of your strongest subjects.`);

  const evening = sessions.filter((s) => {
    const h = s.started_at ? new Date(s.started_at).getHours() : -1;
    return h >= 17;
  }).length;
  if (sessions.length >= 3 && evening > sessions.length / 2) out.push("You usually perform better in the evenings.");

  const weekAgo = new Date();
  weekAgo.setDate(weekAgo.getDate() - 7);
  const weekAgoStr = weekAgo.toISOString().split("T")[0];
  const recentSubjects = new Set(
    sessions.filter((s) => s.session_date && s.session_date >= weekAgoStr).map((s) => s.subject || (s.courses && s.courses[0]))
  );
  const staleCourse = (courses || []).find((c) => c.code && !recentSubjects.has(c.code) && !recentSubjects.has(c.title));
  if (staleCourse) out.push(`You haven't revised ${staleCourse.title || staleCourse.code} this week.`);

  const dates = [...new Set(sessions.filter((s) => s.session_date).map((s) => s.session_date))];
  if (dates.length >= 7) out.push("Your consistency has improved this month. Keep it going.");

  if (out.length === 0) out.push("Add your courses and log a study session, and I'll start spotting patterns for you.");
  return out.slice(0, 4);
}