/** templates — Smart Project Templates registry. Each template seeds a
 *  workspace with folders (collections), smart notes, task lists, a
 *  timeline of milestones, and suggested permissions + workflow. */

export const TEMPLATES = [
  {
    key: "individual_study_plan",
    label: "Individual Study Plan",
    icon: "📘",
    type: "personal",
    color: "221 83% 50%",
    summary: "A personal study plan with weekly goals, revision tasks and a reading schedule.",
    permissions: { default_role: "owner", allow_member_invite: false },
    items: [
      { type: "study_plan", title: "Weekly Study Plan", blocks: [{ week: 1, focus: "Foundations", items: ["Review lecture notes", "Practice problems"] }, { week: 2, focus: "Deep practice", items: ["Past questions", "Flashcards"] }] },
      { type: "checklist", title: "Revision Checklist", blocks: [{ text: "Summarize key concepts", done: false }, { text: "Practice past papers", done: false }] },
      { type: "note", title: "Learning Goals", content: "## Goals\n- What I want to master this semester\n- Target grade\n- Weekly study hours" },
      { type: "task", title: "Weekly review", due_offset: 7, priority: "high" },
    ],
    milestones: [{ title: "Mid-term prep", offset_days: 21 }, { title: "Final revision", offset_days: 49 }],
    workflow: "Plan → Study → Practice → Review → Reflect",
  },
  {
    key: "group_assignment",
    label: "Group Assignment",
    icon: "👥",
    type: "project",
    color: "173 75% 38%",
    summary: "Coordinate a group assignment with divided tasks, shared notes and a deadline timeline.",
    permissions: { default_role: "editor", allow_member_invite: true },
    items: [
      { type: "task", title: "Research section", priority: "high" },
      { type: "task", title: "Draft writing" },
      { type: "task", title: "Editing & proofread" },
      { type: "task", title: "Final submission", priority: "urgent" },
      { type: "document", title: "Shared draft", content: "# Group Assignment\n\n## Introduction\n\n## Body\n\n## Conclusion" },
      { type: "checklist", title: "Submission checklist", blocks: [{ text: "All sections complete", done: false }, { text: "References formatted", done: false }, { text: "Plagiarism check", done: false }] },
    ],
    milestones: [{ title: "Research done", offset_days: 7 }, { title: "First draft", offset_days: 14 }, { title: "Submission", offset_days: 21 }],
    workflow: "Assign → Research → Draft → Review → Submit",
  },
  {
    key: "research_project",
    label: "Research Project",
    icon: "🔬",
    type: "research",
    color: "198 88% 42%",
    summary: "Manage a research project with literature review, methodology, data and write-up milestones.",
    permissions: { default_role: "editor", allow_member_invite: true },
    items: [
      { type: "document", title: "Literature Review", content: "# Literature Review\n\n## Key sources\n\n## Gaps identified" },
      { type: "document", title: "Methodology", content: "# Methodology\n\n## Design\n\n## Data collection\n\n## Analysis" },
      { type: "task", title: "Data collection", priority: "high" },
      { type: "task", title: "Data analysis" },
      { type: "task", title: "Write-up" },
    ],
    milestones: [{ title: "Proposal approved", offset_days: 14 }, { title: "Data collected", offset_days: 45 }, { title: "Analysis complete", offset_days: 75 }, { title: "Defense", offset_days: 100 }],
    workflow: "Proposal → Literature → Data → Analysis → Write-up → Defense",
  },
  {
    key: "lab_report",
    label: "Laboratory Report",
    icon: "🧪",
    type: "project",
    color: "173 75% 38%",
    summary: "Structure a lab report with objectives, procedure, results and discussion.",
    permissions: { default_role: "editor", allow_member_invite: true },
    items: [
      { type: "document", title: "Lab Report", content: "# Laboratory Report\n\n## Objective\n\n## Apparatus\n\n## Procedure\n\n## Results\n\n## Discussion\n\n## Conclusion" },
      { type: "checklist", title: "Lab checklist", blocks: [{ text: "Record raw data", done: false }, { text: "Plot graphs", done: false }, { text: "Error analysis", done: false }] },
    ],
    milestones: [{ title: "Experiment done", offset_days: 3 }, { title: "Report submitted", offset_days: 7 }],
    workflow: "Experiment → Record → Analyze → Report",
  },
  {
    key: "final_year_project",
    label: "Final Year Project",
    icon: "🎓",
    type: "project",
    color: "46 70% 50%",
    summary: "A full FYP timeline from proposal to defense with supervisor milestones.",
    permissions: { default_role: "editor", allow_member_invite: true },
    items: [
      { type: "document", title: "Project Proposal", content: "# Proposal\n\n## Title\n\n## Problem statement\n\n## Objectives\n\n## Methodology\n\n## Timeline" },
      { type: "document", title: "Chapter 1-5 Draft" },
      { type: "task", title: "Weekly supervisor meeting", priority: "high" },
      { type: "task", title: "Prototype / implementation" },
      { type: "task", title: "Testing & evaluation" },
      { type: "study_plan", title: "FYP Timeline", blocks: [{ week: 1, focus: "Proposal", items: ["Literature review", "Problem definition"] }, { week: 6, focus: "Implementation", items: ["Build prototype"] }, { week: 12, focus: "Write-up & defense", items: ["Final chapter", "Defense slides"] }] },
    ],
    milestones: [{ title: "Proposal defense", offset_days: 21 }, { title: "Mid-project review", offset_days: 70 }, { title: "Final defense", offset_days: 140 }],
    workflow: "Proposal → Build → Test → Write → Defend",
  },
  {
    key: "presentation",
    label: "Presentation",
    icon: "🎤",
    type: "project",
    color: "32 92% 48%",
    summary: "Plan a presentation with outline, slides task list and rehearsal schedule.",
    permissions: { default_role: "editor", allow_member_invite: true },
    items: [
      { type: "document", title: "Presentation Outline", content: "# Outline\n\n## Hook\n\n## Key points\n\n## Evidence\n\n## Conclusion\n\n## Q&A prep" },
      { type: "task", title: "Design slides" },
      { type: "task", title: "Rehearse timing" },
      { type: "checklist", title: "Pre-presentation checklist", blocks: [{ text: "Slides final", done: false }, { text: "Notes ready", done: false }, { text: "Timing practiced", done: false }] },
    ],
    milestones: [{ title: "Slides draft", offset_days: 3 }, { title: "Rehearsal", offset_days: 6 }, { title: "Presentation day", offset_days: 7 }],
    workflow: "Outline → Slides → Rehearse → Present",
  },
  {
    key: "meeting_notes",
    label: "Meeting Notes",
    icon: "📝",
    type: "team",
    color: "215 16% 45%",
    summary: "Capture meeting agenda, decisions, action items and follow-ups.",
    permissions: { default_role: "commenter", allow_member_invite: true },
    items: [
      { type: "document", title: "Meeting Notes", content: "# Meeting — [Date]\n\n## Attendees\n\n## Agenda\n\n## Discussion\n\n## Decisions\n\n## Action items\n- [ ] \n\n## Next meeting" },
      { type: "checklist", title: "Action items", blocks: [{ text: "Follow up on...", done: false }] },
    ],
    milestones: [{ title: "Next meeting", offset_days: 7 }],
    workflow: "Agenda → Discuss → Decide → Assign → Follow up",
  },
  {
    key: "revision_plan",
    label: "Revision Plan",
    icon: "🔁",
    type: "personal",
    color: "0 78% 52%",
    summary: "Exam revision plan with topic checklist, practice schedule and flashcards.",
    permissions: { default_role: "owner", allow_member_invite: false },
    items: [
      { type: "checklist", title: "Topics to revise", blocks: [{ text: "Topic 1", done: false }, { text: "Topic 2", done: false }, { text: "Topic 3", done: false }] },
      { type: "study_plan", title: "Revision schedule", blocks: [{ week: 1, focus: "Core topics", items: ["Re-read notes", "Summarize"] }, { week: 2, focus: "Practice", items: ["Past papers", "Timed mocks"] }] },
      { type: "task", title: "Daily flashcards" },
    ],
    milestones: [{ title: "All topics covered", offset_days: 10 }, { title: "Mock exam", offset_days: 14 }],
    workflow: "Topics → Revise → Practice → Mock → Reflect",
  },
  {
    key: "reading_schedule",
    label: "Reading Schedule",
    icon: "📚",
    type: "personal",
    color: "221 83% 50%",
    summary: "Organize weekly reading targets across courses with notes per reading.",
    permissions: { default_role: "owner", allow_member_invite: false },
    items: [
      { type: "checklist", title: "Reading list", blocks: [{ text: "Chapter 1", done: false }, { text: "Chapter 2", done: false }] },
      { type: "note", title: "Reading notes", content: "## Key takeaways\n\n## Questions\n\n## Quotes" },
    ],
    milestones: [{ title: "Finish reading list", offset_days: 21 }],
    workflow: "Read → Note → Summarize → Discuss",
  },
  {
    key: "department_activity",
    label: "Department Activity",
    icon: "🏛️",
    type: "department",
    color: "222 75% 17%",
    summary: "Coordinate department activities, meetings and student tasks.",
    permissions: { default_role: "editor", allow_member_invite: true },
    items: [
      { type: "task", title: "Department meeting prep" },
      { type: "task", title: "Student feedback collection" },
      { type: "document", title: "Activity report", content: "# Department Activity Report\n\n## Summary\n\n## Outcomes\n\n## Next steps" },
    ],
    milestones: [{ title: "Mid-semester review", offset_days: 35 }],
    workflow: "Plan → Execute → Report",
  },
  {
    key: "club_management",
    label: "Club Management",
    icon: "🎪",
    type: "club",
    color: "198 88% 42%",
    summary: "Run a club with event planning, member tasks and executive meetings.",
    permissions: { default_role: "editor", allow_member_invite: true },
    items: [
      { type: "task", title: "Plan next event" },
      { type: "task", title: "Membership drive" },
      { type: "document", title: "Club constitution/notes", content: "# Club\n\n## Mission\n\n## Executives\n\n## Meetings" },
      { type: "checklist", title: "Event checklist", blocks: [{ text: "Venue booked", done: false }, { text: "Publicity done", done: false }] },
    ],
    milestones: [{ title: "Next event", offset_days: 14 }],
    workflow: "Plan → Promote → Execute → Review",
  },
  {
    key: "student_leadership",
    label: "Student Leadership",
    icon: "👑",
    type: "leadership",
    color: "46 70% 50%",
    summary: "Track student government initiatives, meetings and deliverables.",
    permissions: { default_role: "editor", allow_member_invite: true },
    items: [
      { type: "task", title: "Initiative planning" },
      { type: "task", title: "Constituent feedback" },
      { type: "document", title: "Leadership agenda", content: "# Agenda\n\n## Priorities\n\n## Proposals\n\n## Action items" },
    ],
    milestones: [{ title: "Town hall", offset_days: 30 }],
    workflow: "Listen → Propose → Execute → Report",
  },
  {
    key: "event_planning",
    label: "Event Planning",
    icon: "🎉",
    type: "community",
    color: "32 92% 48%",
    summary: "Plan an event end-to-end: budget, logistics, publicity and day-of run sheet.",
    permissions: { default_role: "editor", allow_member_invite: true },
    items: [
      { type: "task", title: "Budget & sponsors" },
      { type: "task", title: "Logistics & venue" },
      { type: "task", title: "Publicity" },
      { type: "checklist", title: "Day-of run sheet", blocks: [{ text: "Setup", done: false }, { text: "Registration", done: false }, { text: "Teardown", done: false }] },
      { type: "document", title: "Event brief", content: "# Event Brief\n\n## Date / venue\n\n## Budget\n\n## Run sheet\n\n## Team" },
    ],
    milestones: [{ title: "Event day", offset_days: 21 }],
    workflow: "Plan → Budget → Promote → Execute → Review",
  },
];

export function getTemplate(key) { return TEMPLATES.find((t) => t.key === key); }