import {
  Users, BookOpen, UserCheck, GraduationCap, Building2, Calendar,
  FileText, Mic, Newspaper, ShoppingBag, Award, MapPin, Brain,
} from "lucide-react";

/**
 * SEARCH_INDEX — the canonical registry of every resource Universal Search
 * indexes. Each entry defines both the query shape (entity + fields + limit)
 * and the display shape (icon + route + title/subtitle extractors).
 *
 * RLS is enforced automatically by the Base44 SDK — only records the
 * authenticated student has permission to read are returned by each
 * entity .list() call.
 */
export const SEARCH_INDEX = [
  {
    key: "students",
    label: "Students",
    entity: "User",
    fields: ["full_name", "email"],
    limit: 6,
    icon: Users,
    route: (r) => (r.id ? `/profile/${r.id}` : "/discover"),
    title: (r) => r.full_name || "Student",
    subtitle: (r) => r.email || "",
    imageField: null,
  },
  {
    key: "courses",
    label: "Courses",
    entity: "Course",
    fields: ["title", "course_code", "description"],
    limit: 6,
    icon: BookOpen,
    route: (r) => (r.id ? `/course/${r.id}` : "/courses"),
    title: (r) => (r.course_code ? `${r.course_code} — ${r.title || ""}`.trim() : r.title || "Course"),
    subtitle: (r) => r.department || "",
    imageField: null,
  },
  {
    key: "lecturers",
    label: "Lecturers",
    entity: "Staff",
    fields: ["name", "role", "department"],
    limit: 6,
    icon: UserCheck,
    route: () => "/directory",
    title: (r) => r.name || "Staff",
    subtitle: (r) => [r.role, r.department].filter(Boolean).join(" · "),
    imageField: null,
  },
  {
    key: "studyGroups",
    label: "Study Groups",
    entity: "StudyGroup",
    fields: ["name", "subject", "description", "course_code"],
    limit: 5,
    icon: GraduationCap,
    route: (r) => (r.id ? `/study-groups/${r.id}` : "/study-groups"),
    title: (r) => r.name || "Study Group",
    subtitle: (r) => r.subject || r.course_code || "",
    imageField: null,
  },
  {
    key: "organizations",
    label: "Organizations",
    entity: "CompanyPage",
    fields: ["name", "tagline", "description", "industry"],
    limit: 5,
    icon: Building2,
    route: () => "/companies",
    title: (r) => r.name || "Organization",
    subtitle: (r) => r.industry || r.tagline || "",
    imageField: "logo_url",
  },
  {
    key: "events",
    label: "Events",
    entity: "CampusEvent",
    fields: ["title", "description", "location"],
    limit: 6,
    icon: Calendar,
    route: () => "/events",
    title: (r) => r.title || "Event",
    subtitle: (r) => [r.location, r.date].filter(Boolean).join(" · "),
    imageField: "image_url",
  },
  {
    key: "files",
    label: "Files",
    entity: "AcademicFile",
    fields: ["title", "description", "subject", "course_code"],
    limit: 6,
    icon: FileText,
    route: () => "/academics/files",
    title: (r) => r.title || "File",
    subtitle: (r) => r.subject || r.course_code || "",
    imageField: "thumbnail_url",
  },
  {
    key: "podcasts",
    label: "Podcasts",
    entity: "Podcast",
    fields: ["title", "description", "host_name", "category"],
    limit: 5,
    icon: Mic,
    route: (r) => (r.id ? `/podcasts/${r.id}` : "/podcasts"),
    title: (r) => r.title || "Podcast",
    subtitle: (r) => r.host_name || r.category || "",
    imageField: "cover_url",
  },
  {
    key: "articles",
    label: "Articles",
    entity: "QuadPost",
    fields: ["content", "author_name"],
    limit: 6,
    icon: Newspaper,
    route: () => "/quad",
    title: (r) => (r.content || "").slice(0, 60) || "Post",
    subtitle: (r) => r.author_name || "",
    imageField: null,
  },
  {
    key: "marketplace",
    label: "Marketplace",
    entity: "MarketplaceListing",
    fields: ["title", "description"],
    limit: 6,
    icon: ShoppingBag,
    route: () => "/marketplace",
    title: (r) => r.title || "Listing",
    subtitle: (r) => (r.is_free ? "Free" : r.price ? `\u20a6${Number(r.price).toLocaleString()}` : r.category || ""),
    imageField: null,
  },
  {
    key: "scholarships",
    label: "Scholarships",
    entity: "Scholarship",
    fields: ["title", "provider", "description"],
    limit: 5,
    icon: Award,
    route: () => "/scholarships",
    title: (r) => r.title || "Scholarship",
    subtitle: (r) => [r.provider, r.amount].filter(Boolean).join(" \u00b7 "),
    imageField: "logo_url",
  },
  {
    key: "buildings",
    label: "Buildings",
    entity: "CampusLocation",
    fields: ["name", "description", "building"],
    limit: 5,
    icon: MapPin,
    route: () => "/campus-map",
    title: (r) => r.name || "Location",
    subtitle: (r) => [r.building, r.category].filter(Boolean).join(" \u00b7 "),
    imageField: "image_url",
  },
  {
    key: "budKnowledge",
    label: "Bud Knowledge",
    entity: "BudMemory",
    fields: ["key", "value", "content", "category"],
    limit: 4,
    icon: Brain,
    route: () => "/memory",
    title: (r) => (r.key ? r.key.replace(/_/g, " ") : "Memory"),
    subtitle: (r) => (r.value || r.content || "").slice(0, 60),
    imageField: null,
  },
];

export const CONFIG_MAP = Object.fromEntries(SEARCH_INDEX.map((c) => [c.key, c]));