export * from './module';
export * from './types';
export * from './services/shared/student.service';
export * from './services/shared/educator.service';
export * from './services/shared/program.service';
export * from './services/shared/subject.service';
export * from './services/shared/class.service';
export * from './services/shared/enrollment.service';
export * from './services/shared/permission.service';
export * from './services/shared/invitation.service';
export * from './services/university/university.service';
export * from './services/university/faculty.service';
export * from './services/university/department.service';
export * from './services/university/course.service';
export * from './services/learning-org/organization.service';
export * from './services/learning-org/learning-program.service';
export { studentRoutes } from './api/shared/students.routes';
export { educatorRoutes } from './api/shared/educators.routes';
export { programRoutes } from './api/shared/programs.routes';
export { subjectRoutes } from './api/shared/subjects.routes';
export { classRoutes } from './api/shared/classes.routes';
export { enrollmentRoutes } from './api/shared/enrollments.routes';
export { permissionRoutes } from './api/shared/permissions.routes';
export { invitationRoutes } from './api/shared/invitations.routes';
export { universityRoutes } from './api/university/universities.routes';
export { facultyRoutes } from './api/university/faculties.routes';
export { departmentRoutes } from './api/university/departments.routes';
export { courseRoutes } from './api/university/courses.routes';
export { organizationRoutes } from './api/learning-org/organizations.routes';
export { learningProgramRoutes } from './api/learning-org/learning-programs.routes';
