/**
 * AI Agent Definitions — Milestone 1 AI Foundation
 *
 * Canonical definitions for all AI agents in the UNIBUD platform.
 * The AI Kernel registers these at boot so every agent participates
 * in the shared lifecycle, health, and event infrastructure.
 *
 * Categories map to platform divisions:
 *   companion      — user-facing conversational interface
 *   orchestration  — runtime coordination and governance
 *   intelligence   — reasoning, knowledge, synthesis
 *   navigation     — domain navigation intelligence
 *   student        — student success and academic intelligence
 *   discovery      — content and media discovery
 *   creator        — creative and production intelligence
 *   marketplace    — commerce and trust intelligence
 *   platform       — cross-cutting platform intelligence
 */

export const AI_AGENT_DEFINITIONS = [
  // ── Core Super Agents ──────────────────────────────────────────────────
  {
    id: "bud",
    name: "Bud",
    category: "companion",
    version: "1.0.0",
    dependencies: ["oracle", "memory", "knowledge", "telemetry"],
    capabilities: ["conversation", "personality", "transcript"],
    permissions: ["model:invoke"],
    description: "Sole user-facing conversational companion. Receives messages, renders responses, routes work through Oracle.",
    communicatesWith: ["oracle"],
  },
  {
    id: "spark",
    name: "Spark",
    category: "orchestration",
    version: "1.0.0",
    dependencies: ["model", "prompt", "memory", "knowledge", "telemetry"],
    capabilities: ["reasoning", "synthesis", "knowledge", "summaries", "writing", "orchestration"],
    permissions: ["model:invoke", "agent:route"],
    description: "Knowledge intelligence and orchestration hub. Coordinates all specialist agents.",
    communicatesWith: ["bud", "oracle", "nexus"],
  },
  {
    id: "oracle",
    name: "Oracle",
    category: "orchestration",
    version: "1.0.0",
    dependencies: ["nexus", "guardian", "telemetry", "audit"],
    capabilities: ["routing", "governance", "pipeline"],
    permissions: ["agent:route", "policy:evaluate"],
    description: "Runtime kernel. Coordinates the pipeline from Bud through Guardian and Nexus.",
    communicatesWith: ["bud", "nexus", "guardian"],
  },
  {
    id: "orbit",
    name: "Orbit",
    category: "orchestration",
    version: "1.0.0",
    dependencies: ["workflow", "configuration", "telemetry"],
    capabilities: ["scheduling", "workflows", "retries", "automation"],
    permissions: ["workflow:execute", "workflow:schedule"],
    description: "Execution management. Handles workflows, scheduling, retries, and long-running jobs.",
    communicatesWith: ["spark", "oracle"],
  },
  {
    id: "lens",
    name: "Lens",
    category: "intelligence",
    version: "1.0.0",
    dependencies: ["search", "knowledge", "model"],
    capabilities: ["search", "discovery", "retrieval", "filtering"],
    permissions: ["model:invoke", "search:query"],
    description: "Search and discovery intelligence. Surfaces relevant content, entities, and knowledge across the platform.",
    communicatesWith: ["spark", "oracle"],
  },
  {
    id: "the_artist",
    name: "The Artist",
    category: "creator",
    version: "1.0.0",
    dependencies: ["model", "media", "storage"],
    capabilities: ["image_generation", "visual_design", "creative_writing", "media_creation"],
    permissions: ["model:invoke", "media:generate", "storage:write"],
    description: "Creative intelligence. Generates images, visual designs, and creative content.",
    communicatesWith: ["spark", "oracle"],
  },
  {
    id: "architect",
    name: "Architect",
    category: "intelligence",
    version: "1.0.0",
    dependencies: ["model", "knowledge", "storage"],
    capabilities: ["product_architecture", "feature_design", "platform_coherence", "technical_planning"],
    permissions: ["model:invoke", "knowledge:write"],
    description: "Platform architecture intelligence. Owns product direction, feature architecture, and coherence.",
    communicatesWith: ["spark", "oracle"],
  },

  // ── Navigation Intelligence ────────────────────────────────────────────
  {
    id: "social_ai",
    name: "Social AI",
    category: "navigation",
    version: "1.0.0",
    dependencies: ["model", "memory", "knowledge"],
    capabilities: ["social_feed", "community", "connections", "posts"],
    permissions: ["model:invoke"],
    description: "Social navigation intelligence. Powers social feed, connections, and community interactions.",
    communicatesWith: ["spark"],
  },
  {
    id: "academics_ai",
    name: "Academics AI",
    category: "navigation",
    version: "1.0.0",
    dependencies: ["model", "memory", "knowledge", "courseLoad"],
    capabilities: ["academic_navigation", "course_discovery", "grade_analysis"],
    permissions: ["model:invoke"],
    description: "Academic navigation intelligence. Guides students through academic journeys.",
    communicatesWith: ["spark"],
  },

  // ── Student Intelligence ───────────────────────────────────────────────
  {
    id: "campus_ai",
    name: "Campus AI",
    category: "student",
    version: "1.0.0",
    dependencies: ["model", "campusKnowledge", "campusIntelligence"],
    capabilities: ["campus_life", "events", "clubs", "facilities"],
    permissions: ["model:invoke"],
    description: "Campus intelligence. Powers campus events, clubs, spaces, and traditions.",
    communicatesWith: ["spark"],
  },
  {
    id: "community_ai",
    name: "Community AI",
    category: "student",
    version: "1.0.0",
    dependencies: ["model", "memory", "knowledge", "studyGroup"],
    capabilities: ["community_building", "study_groups", "peer_connections"],
    permissions: ["model:invoke"],
    description: "Community intelligence. Facilitates peer connections and community building.",
    communicatesWith: ["spark"],
  },
  {
    id: "learning_ai",
    name: "Learning AI",
    category: "student",
    version: "1.0.0",
    dependencies: ["model", "memory", "knowledge", "courseLoad"],
    capabilities: ["learning_paths", "adaptive_learning", "comprehension_check"],
    permissions: ["model:invoke"],
    description: "Learning intelligence. Adapts learning paths and checks comprehension.",
    communicatesWith: ["spark"],
  },
  {
    id: "assignment_ai",
    name: "Assignment AI",
    category: "student",
    version: "1.0.0",
    dependencies: ["model", "memory", "knowledge"],
    capabilities: ["assignment_help", "feedback", "drafting", "review"],
    permissions: ["model:invoke"],
    description: "Assignment intelligence. Helps with drafting, reviewing, and improving assignments.",
    communicatesWith: ["spark"],
  },
  {
    id: "quiz_ai",
    name: "Quiz AI",
    category: "student",
    version: "1.0.0",
    dependencies: ["model", "knowledge"],
    capabilities: ["quiz_generation", "assessment", "adaptive_questions"],
    permissions: ["model:invoke"],
    description: "Quiz intelligence. Generates adaptive quizzes and assessments.",
    communicatesWith: ["spark"],
  },
  {
    id: "library_ai",
    name: "Library AI",
    category: "student",
    version: "1.0.0",
    dependencies: ["model", "knowledge", "search"],
    capabilities: ["resource_discovery", "citation", "research_support"],
    permissions: ["model:invoke", "knowledge:query"],
    description: "Library intelligence. Powers resource discovery, citations, and research support.",
    communicatesWith: ["spark", "lens"],
  },
  {
    id: "research_ai",
    name: "Research AI",
    category: "student",
    version: "1.0.0",
    dependencies: ["model", "knowledge", "search"],
    capabilities: ["research_assistance", "literature_review", "methodology"],
    permissions: ["model:invoke", "knowledge:query"],
    description: "Research intelligence. Assists with research methodology, literature review, and writing.",
    communicatesWith: ["spark", "lens"],
  },
  {
    id: "project_ai",
    name: "Project AI",
    category: "student",
    version: "1.0.0",
    dependencies: ["model", "memory", "knowledge"],
    capabilities: ["project_planning", "task_breakdown", "collaboration"],
    permissions: ["model:invoke"],
    description: "Project intelligence. Helps plan, break down, and track project work.",
    communicatesWith: ["spark", "orbit"],
  },
  {
    id: "study_planner_ai",
    name: "Study Planner AI",
    category: "student",
    version: "1.0.0",
    dependencies: ["model", "memory", "courseLoad", "academicPlanning"],
    capabilities: ["study_scheduling", "exam_prep", "time_management"],
    permissions: ["model:invoke"],
    description: "Study planning intelligence. Creates personalized study schedules and exam preparation plans.",
    communicatesWith: ["spark", "orbit"],
  },
  {
    id: "revision_ai",
    name: "Revision AI",
    category: "student",
    version: "1.0.0",
    dependencies: ["model", "memory", "knowledge"],
    capabilities: ["revision_planning", "topic_consolidation", "spaced_repetition"],
    permissions: ["model:invoke"],
    description: "Revision intelligence. Structures revision using spaced repetition and topic consolidation.",
    communicatesWith: ["spark"],
  },
  {
    id: "flashcard_ai",
    name: "Flashcard AI",
    category: "student",
    version: "1.0.0",
    dependencies: ["model", "knowledge"],
    capabilities: ["flashcard_generation", "deck_management", "active_recall"],
    permissions: ["model:invoke"],
    description: "Flashcard intelligence. Generates flashcard decks and supports active recall practice.",
    communicatesWith: ["spark"],
  },

  // ── Discovery Intelligence ─────────────────────────────────────────────
  {
    id: "news_ai",
    name: "News AI",
    category: "discovery",
    version: "1.0.0",
    dependencies: ["model", "knowledge", "search"],
    capabilities: ["news_discovery", "summarization", "relevance_ranking"],
    permissions: ["model:invoke"],
    description: "News intelligence. Discovers, summarizes, and ranks relevant news for students.",
    communicatesWith: ["spark", "lens"],
  },
  {
    id: "podcast_ai",
    name: "Podcast AI",
    category: "discovery",
    version: "1.0.0",
    dependencies: ["model", "knowledge", "media"],
    capabilities: ["podcast_discovery", "episode_summaries", "topic_matching"],
    permissions: ["model:invoke"],
    description: "Podcast intelligence. Discovers relevant podcasts and summarizes episodes.",
    communicatesWith: ["spark", "lens"],
  },
  {
    id: "movies_ai",
    name: "Movies AI",
    category: "discovery",
    version: "1.0.0",
    dependencies: ["model", "knowledge"],
    capabilities: ["movie_discovery", "recommendations", "reviews"],
    permissions: ["model:invoke"],
    description: "Movies intelligence. Discovers and recommends movies relevant to student interests.",
    communicatesWith: ["spark", "lens"],
  },
  {
    id: "anime_ai",
    name: "Anime AI",
    category: "discovery",
    version: "1.0.0",
    dependencies: ["model", "knowledge"],
    capabilities: ["anime_discovery", "recommendations", "series_summaries"],
    permissions: ["model:invoke"],
    description: "Anime intelligence. Discovers and recommends anime series.",
    communicatesWith: ["spark", "lens"],
  },
  {
    id: "sports_ai",
    name: "Sports AI",
    category: "discovery",
    version: "1.0.0",
    dependencies: ["model", "knowledge"],
    capabilities: ["sports_updates", "team_tracking", "event_notifications"],
    permissions: ["model:invoke"],
    description: "Sports intelligence. Tracks sports, teams, and delivers relevant updates.",
    communicatesWith: ["spark", "lens"],
  },

  // ── Creator Intelligence ───────────────────────────────────────────────
  {
    id: "creator_ai",
    name: "Creator AI",
    category: "creator",
    version: "1.0.0",
    dependencies: ["model", "media", "storage"],
    capabilities: ["content_creation", "ideation", "production_planning"],
    permissions: ["model:invoke", "media:read"],
    description: "Creator intelligence. Helps plan and produce original content.",
    communicatesWith: ["spark", "the_artist"],
  },
  {
    id: "camera_ai",
    name: "Camera AI",
    category: "creator",
    version: "1.0.0",
    dependencies: ["model", "media"],
    capabilities: ["photo_analysis", "camera_guidance", "visual_feedback"],
    permissions: ["model:invoke", "media:read"],
    description: "Camera intelligence. Analyzes photos and provides visual creation guidance.",
    communicatesWith: ["spark", "the_artist"],
  },
  {
    id: "voice_ai",
    name: "Voice AI",
    category: "creator",
    version: "1.0.0",
    dependencies: ["model", "media"],
    capabilities: ["voice_transcription", "voice_synthesis", "audio_analysis"],
    permissions: ["model:invoke", "media:transcribe"],
    description: "Voice intelligence. Transcribes, synthesizes, and analyzes voice content.",
    communicatesWith: ["spark"],
  },
  {
    id: "language_ai",
    name: "Language AI",
    category: "creator",
    version: "1.0.0",
    dependencies: ["model", "knowledge"],
    capabilities: ["translation", "grammar_check", "language_learning", "writing_enhancement"],
    permissions: ["model:invoke"],
    description: "Language intelligence. Handles translation, grammar, and writing enhancement.",
    communicatesWith: ["spark"],
  },
  {
    id: "media_ai",
    name: "Media AI",
    category: "creator",
    version: "1.0.0",
    dependencies: ["model", "media", "storage"],
    capabilities: ["media_analysis", "content_moderation", "format_conversion"],
    permissions: ["model:invoke", "media:read", "storage:read"],
    description: "Media intelligence. Analyzes, moderates, and manages media assets.",
    communicatesWith: ["spark", "the_artist"],
  },

  // ── Marketplace Intelligence ───────────────────────────────────────────
  {
    id: "marketplace_ai",
    name: "Marketplace AI",
    category: "marketplace",
    version: "1.0.0",
    dependencies: ["model", "knowledge", "recommendation"],
    capabilities: ["listing_discovery", "price_analysis", "seller_matching"],
    permissions: ["model:invoke"],
    description: "Marketplace intelligence. Discovers listings, analyzes prices, and matches buyers/sellers.",
    communicatesWith: ["spark"],
  },
  {
    id: "commerce_ai",
    name: "Commerce AI",
    category: "marketplace",
    version: "1.0.0",
    dependencies: ["model", "knowledge", "storage"],
    capabilities: ["transaction_intelligence", "fraud_signals", "payment_guidance"],
    permissions: ["model:invoke"],
    description: "Commerce intelligence. Powers transaction intelligence and payment guidance.",
    communicatesWith: ["spark"],
  },
  {
    id: "trust_safety_ai",
    name: "Trust & Safety AI",
    category: "marketplace",
    version: "1.0.0",
    dependencies: ["model", "audit", "analytics"],
    capabilities: ["content_moderation", "trust_scoring", "safety_review"],
    permissions: ["model:invoke", "audit:write"],
    description: "Trust & Safety intelligence. Moderates content and enforces community safety.",
    communicatesWith: ["spark", "oracle"],
  },

  // ── Student Success Intelligence ───────────────────────────────────────
  {
    id: "career_ai",
    name: "Career AI",
    category: "student",
    version: "1.0.0",
    dependencies: ["model", "memory", "careerIntelligence", "opportunityEngine"],
    capabilities: ["career_guidance", "cv_review", "opportunity_matching"],
    permissions: ["model:invoke"],
    description: "Career intelligence. Guides professional development and opportunity matching.",
    communicatesWith: ["spark"],
  },
  {
    id: "scholarship_ai",
    name: "Scholarship AI",
    category: "student",
    version: "1.0.0",
    dependencies: ["model", "knowledge", "opportunityEngine"],
    capabilities: ["scholarship_discovery", "eligibility_check", "application_help"],
    permissions: ["model:invoke"],
    description: "Scholarship intelligence. Discovers scholarships and assists with applications.",
    communicatesWith: ["spark"],
  },
  {
    id: "wellness_ai",
    name: "Wellness AI",
    category: "student",
    version: "1.0.0",
    dependencies: ["model", "memory"],
    capabilities: ["mental_health_support", "stress_management", "wellbeing_insights"],
    permissions: ["model:invoke"],
    description: "Wellness intelligence. Supports mental health and wellbeing with empathetic guidance.",
    communicatesWith: ["spark"],
  },
  {
    id: "gamification_ai",
    name: "Gamification AI",
    category: "student",
    version: "1.0.0",
    dependencies: ["model", "analytics", "recommendation"],
    capabilities: ["achievement_tracking", "challenge_design", "reward_optimization"],
    permissions: ["model:invoke"],
    description: "Gamification intelligence. Designs challenges, tracks achievements, and optimizes rewards.",
    communicatesWith: ["spark"],
  },
  {
    id: "opportunity_ai",
    name: "Opportunity AI",
    category: "student",
    version: "1.0.0",
    dependencies: ["model", "memory", "opportunityEngine", "careerIntelligence"],
    capabilities: ["opportunity_discovery", "personalized_matching", "application_guidance"],
    permissions: ["model:invoke"],
    description: "Opportunity intelligence. Discovers and matches students to opportunities.",
    communicatesWith: ["spark"],
  },

  // ── Platform Intelligence ──────────────────────────────────────────────
  {
    id: "recommendation_ai",
    name: "Recommendation AI",
    category: "platform",
    version: "1.0.0",
    dependencies: ["model", "memory", "recommendation", "personalKnowledgeGraph"],
    capabilities: ["content_recommendations", "peer_recommendations", "resource_recommendations"],
    permissions: ["model:invoke"],
    description: "Recommendation intelligence. Personalizes content and resource recommendations.",
    communicatesWith: ["spark"],
  },
  {
    id: "moderation_ai",
    name: "Moderation AI",
    category: "platform",
    version: "1.0.0",
    dependencies: ["model", "audit", "analytics"],
    capabilities: ["content_moderation", "policy_enforcement", "flagging"],
    permissions: ["model:invoke", "audit:write"],
    description: "Moderation intelligence. Automatically reviews and moderates platform content.",
    communicatesWith: ["spark", "oracle"],
  },
  {
    id: "security_ai",
    name: "Security AI",
    category: "platform",
    version: "1.0.0",
    dependencies: ["model", "audit", "analytics"],
    capabilities: ["threat_detection", "anomaly_detection", "incident_response"],
    permissions: ["model:invoke", "audit:write", "security:alert"],
    description: "Security intelligence. Detects threats, anomalies, and coordinates incident response.",
    communicatesWith: ["spark", "oracle"],
  },
  {
    id: "privacy_ai",
    name: "Privacy AI",
    category: "platform",
    version: "1.0.0",
    dependencies: ["model", "audit", "identity"],
    capabilities: ["data_governance", "consent_management", "privacy_review"],
    permissions: ["model:invoke", "audit:write"],
    description: "Privacy intelligence. Enforces data governance and consent management.",
    communicatesWith: ["spark", "oracle"],
  },
  {
    id: "analytics_ai",
    name: "Analytics AI",
    category: "platform",
    version: "1.0.0",
    dependencies: ["model", "analytics", "metrics", "telemetry"],
    capabilities: ["trend_analysis", "predictive_insights", "reporting"],
    permissions: ["model:invoke", "analytics:read"],
    description: "Analytics intelligence. Surfaces trends, predictions, and platform insights.",
    communicatesWith: ["spark"],
  },
  {
    id: "automation_ai",
    name: "Automation AI",
    category: "platform",
    version: "1.0.0",
    dependencies: ["model", "autonomousTaskEngine", "workflow"],
    capabilities: ["workflow_automation", "task_automation", "trigger_management"],
    permissions: ["model:invoke", "workflow:execute"],
    description: "Automation intelligence. Designs and executes automated workflows and tasks.",
    communicatesWith: ["spark", "orbit"],
  },
  {
    id: "notification_ai",
    name: "Notification AI",
    category: "platform",
    version: "1.0.0",
    dependencies: ["model", "notification", "analytics"],
    capabilities: ["smart_notifications", "notification_timing", "preference_learning"],
    permissions: ["model:invoke", "notification:send"],
    description: "Notification intelligence. Personalizes and optimizes notification delivery.",
    communicatesWith: ["spark"],
  },
  {
    id: "integration_ai",
    name: "Integration AI",
    category: "platform",
    version: "1.0.0",
    dependencies: ["model", "integrations"],
    capabilities: ["integration_health", "connector_orchestration", "data_sync"],
    permissions: ["model:invoke", "integration:read"],
    description: "Integration intelligence. Monitors integration health and orchestrates connectors.",
    communicatesWith: ["spark"],
  },
  {
    id: "identity_ai",
    name: "Identity AI",
    category: "platform",
    version: "1.0.0",
    dependencies: ["model", "identity", "audit"],
    capabilities: ["identity_verification", "access_decisions", "role_analysis"],
    permissions: ["model:invoke", "identity:read"],
    description: "Identity intelligence. Verifies identities and supports access decisions.",
    communicatesWith: ["spark", "oracle"],
  },
  {
    id: "memory_ai",
    name: "Memory AI",
    category: "platform",
    version: "1.0.0",
    dependencies: ["model", "memory", "personalKnowledgeGraph"],
    capabilities: ["memory_consolidation", "episodic_recall", "semantic_indexing"],
    permissions: ["model:invoke", "memory:read", "memory:write"],
    description: "Memory intelligence. Consolidates, retrieves, and indexes user memories.",
    communicatesWith: ["spark"],
  },
  {
    id: "knowledge_ai",
    name: "Knowledge AI",
    category: "platform",
    version: "1.0.0",
    dependencies: ["model", "knowledge", "campusKnowledge"],
    capabilities: ["knowledge_curation", "gap_detection", "content_enrichment"],
    permissions: ["model:invoke", "knowledge:read", "knowledge:write"],
    description: "Knowledge intelligence. Curates, enriches, and detects gaps in the knowledge base.",
    communicatesWith: ["spark", "lens"],
  },
  {
    id: "context_ai",
    name: "Context AI",
    category: "platform",
    version: "1.0.0",
    dependencies: ["model", "memory", "identity"],
    capabilities: ["context_assembly", "context_compression", "relevance_scoring"],
    permissions: ["model:invoke"],
    description: "Context intelligence. Assembles, compresses, and scores context for agent requests.",
    communicatesWith: ["spark"],
  },
  {
    id: "workflow_ai",
    name: "Workflow AI",
    category: "platform",
    version: "1.0.0",
    dependencies: ["model", "workflow", "orbit"],
    capabilities: ["workflow_design", "process_optimization", "dependency_resolution"],
    permissions: ["model:invoke", "workflow:read"],
    description: "Workflow intelligence. Designs workflows and resolves process dependencies.",
    communicatesWith: ["spark", "orbit"],
  },
  {
    id: "event_ai",
    name: "Event AI",
    category: "platform",
    version: "1.0.0",
    dependencies: ["model", "analytics", "telemetry"],
    capabilities: ["event_analysis", "event_routing", "pattern_detection"],
    permissions: ["model:invoke", "events:read"],
    description: "Event intelligence. Analyzes event streams, routes events, and detects patterns.",
    communicatesWith: ["spark", "oracle"],
  },
];

/** Index by id for O(1) lookups. */
export const AI_AGENTS_BY_ID = Object.fromEntries(
  AI_AGENT_DEFINITIONS.map((a) => [a.id, a])
);
